export { TelegramAPI } from "./TelegramAPI";
export {
  TMessageCallback,
  TInlineQueryCallback,
  TChosenInlineResultCallback,
  TCallbackQueryCallback,
  TShippingQueryCallback,
  TPreCheckoutQueryCallback,
  TPollCallback,
  TPollAnswerCallback,
  TOnError,
  IMessageId,
  LocalFile,
  ActionType,
  TelegramEvents,
} from "./types";

export {
  sendPollOptions,
  sendMessageOptions,
  forwardMessageOptions,
  copyMessageOptions,
  sendPhotoOptions,
  sendAudioOptions,
  sendVideoOptions,
  sendDocumentOptions,
  sendAnimationOptions,
  sendVoiceOptions,
  sendVideoNoteOptions,
  sendMediaGroupOptions,
  sendLocationOptions,
  editMessageLiveLocationOptions,
  stopMessageLiveLocationOptions,
  sendVenueOptions,
  sendContactOptions,
  sendDiceOptions,
  getUserProfilePhotosOptions,
  setMyCommandsOptions,
  banChatMemberOptions,
  restrictChatMemberOptions,
  promoteChatMemberOptions,
  createChatInviteLinkOptions
} from "./methodsOptions";
